apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flight-plan-client.fullname" . }}-configmap
type: Opaque
data:
  REACT_APP_BASE_API_URL: "{{ .Values.data.REACT_APP_BASE_API_URL | default "" }}"
