apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-plan-api.fullname" . }}-secrets
type: Opaque
data:
  DB_URL: "{{ .Values.secrets.DB_URL | default "" | b64enc }}"
  DB_USER: "{{ .Values.secrets.DB_USER | default "" | b64enc }}"
  DB_PASS: "{{ .Values.secrets.DB_PASS | default "" | b64enc }}"
  DB_SCHEMA: "{{ .Values.secrets.DB_SCHEMA | default "" | b64enc }}"
